apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: cloudcart

  template:
    metadata:
      labels:
        app: cloudcart

    spec:
      containers:
      - name: cloudcart
        image: cloudcart:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 5000
        
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3  
