pipeline {
    agent any

    environment {
        PROJECT_DIR = "${WORKSPACE}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Format Check') {
            steps {
                dir('terraform') {
                    sh 'terraform fmt -check'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh 'terraform init -backend=false'
                    sh 'terraform validate'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t cloudcart:latest app
                '''
            }
        }

        stage('Deploy with Ansible') {
            steps {
                dir('ansible') {
                    sh '''
                    ansible-playbook \
                    -i inventory/hosts \
                    playbooks/site.yml
                    '''
                }
            }
        }

        stage('Verify Containers') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no \
                -i /var/lib/jenkins/.ssh/rhel.pem \
                ec2-user@15.206.191.133 \
                "docker ps"
                '''
            }
        }

        stage('Application Health Check') {
            steps {
                sh '''
                curl --fail http://15.206.191.133
                '''
            }
        }

    }

    post {

        success {
            echo "CloudCart Deployment Successful"
        }

        failure {
            echo "Deployment Failed"

            sh '''
            ssh -o StrictHostKeyChecking=no \
            -i /var/lib/jenkins/.ssh/rhel.pem \
            ec2-user@15.206.191.133 \
            "cd ~/cloudcart-devops-platform/app && docker-compose restart"
            '''
        }
    }
}
