---
- name: Install Git
  dnf:
    name: git
    state: present

- name: Install Docker
  dnf:
    name: docker
    state: present

- name: Start Docker
  service:
    name: docker
    state: started

- name: Enable Docker
  service:
    name: docker
    enabled: yes
